services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./evaluation_data:/app/evaluation_data
      - ./logs:/app/logs
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000